<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Pravins-MacBook-Pro.local" failures="4" tests="6" name="runner.TestRunner" time="274.241" errors="0" timestamp="2024-06-12T09:56:44 IST" skipped="0">
  <testcase classname="runner.TestRunner" name="runScenario" time="49.836"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="42.671">
    <failure message="expected [https://debugautomation.com/Home.html] but found [https://debugautomation.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://debugautomation.com/Home.html] but found [https://debugautomation.com/]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at stepDefination.LoginStep.user_will_verify_homepage(LoginStep.java:47)
at ✽.user will verify homepage(file:///Users/pravintambare/Documents/workspace-spring-tool-suite-4-4.13.1.RELEASE/Framework2324/src/test/resources/feature/Login2.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.TestRunner" name="runScenario" time="42.916">
    <failure message="expected [https://debugautomation.com/Home.html] but found [https://debugautomation.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://debugautomation.com/Home.html] but found [https://debugautomation.com/]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at stepDefination.LoginStep.user_will_verify_homepage(LoginStep.java:47)
at ✽.user will verify homepage(file:///Users/pravintambare/Documents/workspace-spring-tool-suite-4-4.13.1.RELEASE/Framework2324/src/test/resources/feature/Login.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.TestRunner" name="runScenario" time="49.181"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="44.773">
    <failure message="expected [https://debugautomation.com/Home.html] but found [https://debugautomation.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://debugautomation.com/Home.html] but found [https://debugautomation.com/]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at stepDefination.LoginStep.user_will_verify_homepage(LoginStep.java:47)
at ✽.user will verify homepage(file:///Users/pravintambare/Documents/workspace-spring-tool-suite-4-4.13.1.RELEASE/Framework2324/src/test/resources/feature/Login2.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.TestRunner" name="runScenario" time="44.864">
    <failure message="expected [https://debugautomation.com/Home.html] but found [https://debugautomation.com/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://debugautomation.com/Home.html] but found [https://debugautomation.com/]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at stepDefination.LoginStep.user_will_verify_homepage(LoginStep.java:47)
at ✽.user will verify homepage(file:///Users/pravintambare/Documents/workspace-spring-tool-suite-4-4.13.1.RELEASE/Framework2324/src/test/resources/feature/Login2.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- runner.TestRunner -->
